version: 0.1
default:
  deploy:
    parameters:
      stack_name: SchedulerStack
      resolve_s3: true
      s3_prefix: SchedulerStack
      region: ca-central-1
      confirm_changeset: true
      capabilities: CAPABILITY_IAM
      disable_rollback: true

