AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Task Scheduler (Layered Architecture)

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Environment:
      Variables:
        TASK_TABLE_NAME: TaskTable

Resources:
  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TaskTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: task_id
          AttributeType: S
      KeySchema:
        - AttributeName: task_id
          KeyType: HASH

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.api
      Events:
        ScheduleTaskApi:
          Type: Api
          Properties:
            Path: /schedule-task
            Method: post

  SchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.scheduler
      Events:
        SchedulerRule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Environment:
        Variables:
          EXECUTE_TASK_FUNCTION: !Ref ExecutorFunction

  ExecutorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.executor
